name: CI/CD wxWidgets with vcpkg

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

permissions: 
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: action/checkout@v2
#      with: 
#        submodules: true #Needed to fetch the vcpkg submodule

#    - name: Bootstrap vcpkg
#      run: ./vcpkg/bootstrap-vcpkg.sh

#    - name: Restore vcpkg cache
#      uses: lukka/run-vcpkg@v10
#      with:
#        doNotRunVcpkgInstall: true # Let CMake do the install

#    - name: Configure and build with CMake
#      uses: lukka/run-cmake@v10
#      with:
#        buildDirectory: ${{ github.workshop }}/build
#        configurePreset: 'default' # Use your CMakePresets.json
#        # vcpkg-root is automatically found when used as a submodule

#    - name: Upload binary artifact
#      uses: action/upload-artifact@v4
#      with:
#        name: Calc_App-binary
#        path: ${{ github.workspace }}/build/Calc_App

#  deploy:
#    runs-on: ubuntu-latest
#    needs: build
#    if: github.event_name == 'push' && github.ref == 'refs/heads/development'

#    steps:
#    - name: Download build artifact
#      uses: actions/download-artifact@v4
#      with:
#        name: Calc_App-binary

#    - name: Run Docker build and push
#      run: |
#        docker build -t coderedranger/Calc_App: latest . #docker username
#        # Uncomment and configure if pushing to Docker Hub
#        # echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
#        # docker push CodeRedRanger/Calc_App:latest

#        # push to itch IO
      
        

    

      
      
