name: CI/CD wxWidgets with vcpkg

on:
  push:
    branches: [development]
  release:
    types: [created]

jobs:
  release_web:
    name: Web Release
    runs-on: windows-latest
    env:
      ACTIONS_STEP_DEBUG: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clean build directory
        run: |
          rmdir /s "${{ github.workspace }}\build"
     #  run: rm -f build/CMakeCache.txt
     #    run: rm -rf ${{ github.workspace }}/build

      - name: Create Build Directory
        run: cmake -E make_directory ${{ github.workspace }}/build
        
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2

      - name: Build wxWidgets project
        shell: msys2 {0}
        run: |
         mkdir build
         cd build
         cmake .. -G "MinGW Makefiles"
         make

      - name: Package application
        run: |
          Compress-Archive -Path "build/Calc_App.exe" -DestinationPath "Calc_App-Windows.zip"

      - name: Download Butler
        run: |
          curl -o butler.zip https://broth.itch.ovh/butler/windows-amd64/LATEST/archive/default
          Expand-Archive butler.zip -DestinationPath butler_cli

      - name: Upload to itch.io
        env: 
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: |
         ./butler_cli/butler push Calc_App-Windows.zip CodeRedRanger/Calc_App:windows-build
   

        

    

      
      
