name: CI/CD wxWidgets with vcpkg

on:
  push:
    branches: [development]
  release:
    types: [created]

jobs:
  release_web:
    name: Web Release
    runs-on: windows-latest
    env:
      ACTIONS_STEP_DEBUG: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            git
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-wxwidgets3.2-msw
            zip
            unzip
            curl

      - name: Clean and create build directory
        shell: msys2 {0}
        run: |
          set -e
          rm -rf build || true
          mkdir build


      - name: Build wxWidgets project with CMake
        shell: msys2 {0}
        run: |
         cd build
         cmake .. -G "MinGW Makefiles"
         make

      - name: Package application
        run: |
          cd build
          zip -r Calc_App-Windows.zip *
          #Compress-Archive -Path "build/Calc_App.exe" -DestinationPath "Calc_App_windows.zip"

      - name: Download Butler
        run: |
          curl -o butler.zip https://broth.itch.ovh/butler/windows-amd64/LATEST/archive/default
          unzip butler.zip

      - name: Upload to itch.io
        shell: msys2 {0}
        env: 
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: |
         ./butler push build/Calc_App_windows.zip CodeRedRanger/Calc_App:windows
   

        

    

      
      
