#restored old yaml. Yaml before this is my last iteration of ahilss attempt

name: Release Build

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]
    types: [closed]

jobs:

  release_web:
    name: Web Release
    runs-on: ubuntu-latest
    env:
      VCPKG_ROOT: ${{ github.workspace }}
      ACTIONS_STEP_DEBUG: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Packages
        run: |
          sudo apt-get update -qq
          sudo apt-get update 
          sudo apt-get install -y  gcc-multilib python3 curl zip unzip
          #sudo apt-get install -y --no-install-recommends libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libxfixes-dev libgl1-mesa-dev
          sudo apt-get install -y libtool
          sudo apt install -y build-essential #libwxgtk3.0-gtk3-dev 
          sudo apt install autoconf automake libtool
          sudo apt-get install -y build-essential cmake git curl unzip
          sudo apt-get install libtool libltdl-dev
          libtoolize --force
          sudo apt install libgtk-3-dev
          #aclocal
          #autoheader
          #automake --add-missing --force-missing
          #autoconf
          
      - name: Clean build directory
        run: rm -f build/CMakeCache.txt
        #run: rm -rf ${{ github.workspace }}\build

      - name: Create Build Directory
        run: cmake -E make_directory ${{ github.workspace }}\build

      - name: Checkout emsdk and configure
        run: |
          git clone https://github.com/emscripten-core/emsdk.git ${{ github.workspace }}/emsdk 
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          echo "EMSDK=$(pwd)" >> $GITHUB_ENV
          source ./emsdk_env.sh
        shell: bash

      - name: Install vcpkg 
        run: |
          git clone https://github.com/microsoft/vcpkg.git  #${{ github.workspace }}/vcpkg
          cd vcpkg
          ./bootstrap-vcpkg.sh
          echo "VCPKG_ROOT=$(pwd)" >> $GITHUB_ENV
          #vcpkg install #use with json file
        shell: bash #pwsh

      - name: Create vcpkg custom triplet for Emscripten
        run: |
          echo "set(VCPKG_CMAKE_SYSTEM_NAME Emscripten)" > "{{ env.VCPKG_ROOT }}/triplets/wasm32-emscripten.cmake" 
          
      - name: Installs including wxWidgets via vcpkg
        run: |
          ${{ github.workspace }}/vcpkg/vcpkg install wxwidgets # --recurse #   vcpkg install #--triplet=x64-linux
        # look at prior build to see how environment was set up
        shell: bash
        # shell: pwsh
         
      #- name: Integrate vcpkg
      #  run: vcpkg integrate install

      - name: Configure CMake with chained toolchains
        run: |
          mkdir build
          cd build
          emcmake cmake .. \
            -DCMAKE_BUILD_TYPE=Release -Wno-dev TOOLCHAIN_FILE=$(( env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake \#-S .  -B ./build 
            -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=${{ env.EMSDK }}/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake \
            -DVCPKG_TARGET_TRIPLET=wasm32-emscripten
           shell: bash 
           
      - name: Build project with Emscripten
        run: |
         cd build
         emmake make
        shell: bash 
        
        #cmake --build ./build --config Release

      - name: Create Artifact
        run: |
          mkdir release
          cp build/Calc_App.html release/index.html
          cp build/Calc_App.js release/Main.js
          cp build/Calc_App.wasm release/Main.wasm
          
      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-release
          path: release

      - name: Install Butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler -V
      - name: Create release zip and run Butler

        # Here we say that we will use the BUTLER_API_KEY as an environment variable
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: |
          cd release
          zip -r ../release.zip *
          cd ..
          # Butler will read the API key from the environment variable
          ./butler login
          ./butler push release.zip CodeRedRanger/Calc_App:html5
          ./butler logout
          
          #cmake -DwxWidgets_CONFIG_EXECUTABLE=${{ github.workspace }}/vcpkg_installed/x64-windows/share/wxwidgets
    
