name: Release Build

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]
    types: [closed]

jobs:

      
      #- name: Install wxWidgets with vcpkg #can't get this to work without json file configed properly
      #  uses: lukka/run-vcpkg@v11
      #  with: 
      #    runVcpkgInstall: true
         # vcpkgJsonGlob: /home/runner/work/Calculator/vcpkg #not needed
       #   vcpkgArguments: 'install wxwidgets:x64-windows-static'
          
  

  release_web:
    name: Web Release
    runs-on: ubuntu-latest
    env:
      VCPKG_ROOT: ${{ github.workspace }}
      ACTIONS_STEP_DEBUG: true

    steps:
      - uses: actions/checkout@v4

      - name: Install Packages
        run: |
          sudo apt-get update -qq
          sudo apt-get update 
          sudo apt-get install -y  gcc-multilib python3 curl zip unzip
          #sudo apt-get install -y --no-install-recommends libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libxfixes-dev libgl1-mesa-dev
          sudo apt-get install -y libtool
          sudo apt install -y build-essential #libwxgtk3.0-gtk3-dev 
          sudo apt install autoconf automake libtool
          sudo apt-get install -y build-essential cmake git curl unzip
          sudo apt-get install libtool libltdl-dev
          libtoolize --force
          sudo apt install libgtk-3-dev
          #aclocal
          #autoheader
          #automake --add-missing --force-missing
          #autoconf
      - name: Clean build directory
        run: rm -f build/CMakeCache.txt
        #run: rm -rf ${{ github.workspace }}\build

      - name: Create Build Directory
        run: cmake -E make_directory ${{ github.workspace }}\build

     # - name: Install vcpkg 
      #  shell: pwsh
       # run: |
        #  git clone https://github.com/microsoft/vcpkg.git ${{ github.workspace }}/vcpkg
         # cd ${{ github.workspace }}/vcpkg
          #./bootstrap-vcpkg.sh
          #already commented out
          #cd ${{ github.workspace }}
          #vcpkg install

      #already commented out
      #- name: Set up CMake toolchain file
       # run: |
        # echo "CMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-linux #>> $GITHUB_ENV # -S .  -B ./build 
        

      #- name: Installs including wxWidgets via vcpkg
       # shell: pwsh
        #run: |
         # ${{ github.workspace }}/vcpkg/vcpkg install wxwidgets # --recurse #   vcpkg install #--triplet=x64-linux
         
      #- name: Integrate vcpkg
      #  run: vcpkg integrate install

      #- name: Checkout emsdk
      #  run: git clone https://github.com/emscripten-core/emsdk.git ${{ github.workspace }}/emsdk

      - name: Install Emscripten
        run: |
          git clone https://github.com/emscripten-core/emsdk.git 
          cd emsdk
          ./emsdk/emsdk install latest
          ./emsdk/emsdk activate latest
          source ./emsdk_env.sh
        shell: bash

      - name: Configure Emscripten environment
        run: |
          source emsdk/emsdk_env.sh
          shell: bash

        

      #- name: Setup Emscripten SDK
      #  uses: mymindstorm/setup-emsdk@v12
      #  id: setup-emsdk
      #  with:
      #    version: 'latest'
          #actions-cache-folder: 'emsdk-cache'

      - name: Clone and Build WxWidgets wasm
        run: |
          source emsdk/emsdk_env.sh
          git clone http://github.com/ahilss/wxWidgets-wasm.git
          cd wxWidgets-wasm
          git submodule update --init src/jpeg
          git submodule update --init 3rdparty/catch
          export CONFIGURE_ARGS=" --host=emscripten --with-cxx=14 --enable-utf8 --enable-universal--disable-shared --disable-exceptions --disable-richtext --without-libtiff --disable-xlocale"
          emconfigure ./configure $CONFIGURE_ARGS
          emmake make -j$(nproc)
          cd ..
        shell: bash  
        #uses: ahilss/wxWidgets-wasm@v12
        #id: setup-wxwidgets-wasm
        #with:
        #  version: 'latest'
        #  actions-cache-folder: 'wxWidgets-cache'

      - name: Build wxWidgets app
        run: |
          source emsdk/emsdk_env.sh
          mkdir build && cd build
          emcmake cmake ..
          emmake make
          
      #- name: Configure CMake
      #  run: |
      #    emcmake cmake -S . -B build "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=${{ github.workspace }}/build/emsdk-cache/cmake/Modules/Platform/Emscripten.cmake" "-DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake" #"-DVCPKG_TARGET_TRIPLET=wasm32-emscripten"
      #    emcmake cmake -S . -B build "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=${{ steps.setup-emsdk.outputs.emscripten-path}}/cmake/Modules/Platform/Emscripten.cmake" "-DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/build/wxWidgets-cache/cmake/Modules/Platform/Emscripten.cmake" #"-DVCPKG_TARGET_TRIPLET=wasm32-emscripten"
          #cmake -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake -S .  -B ./build 
          #cmake -DwxWidgets_CONFIG_EXECUTABLE=${{ github.workspace }}/vcpkg_installed/x64-windows/share/wxwidgets
    
     # - name: Build 
      #  run: cmake --build build #./build --config Release

      - name: Create Artifact
        run: |
          mkdir release
          pwd
          ls -R
          cp build/Calc_App.html release/index.html
          cp build/Calc_App.js release/Main.js
          cp build/Calc_App.wasm release/Main.wasm
      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-release
          path: release

      - name: Install Butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler -V
      - name: Create release zip and run Butler

        # Here we say that we will use the BUTLER_API_KEY as an environment variable
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: |
          cd release
          zip -r ../release.zip *
          cd ..
          # Butler will read the API key from the environment variable
          ./butler login
          ./butler push release.zip CodeRedRanger/Calc_App:html5
          ./butler logout
